export const categories = [
    "Electronics",
    "Shoes",
  "Phones",
    "Food-Bakery",
    "Computer-accessories",
    "BluetoothSpeakers",
    "Phonecovers",
    "Gaming",
    "Earphones",
    "Earpods",
    "Phone-accessories",
    "Men's Clothing",
    "Cleaning-Supplies",
    "Women's Clothing",
    "Books",
    "Luggages-Bags",
    "Home-Kitchen",
    "Toys-Entertainment",
    "Beauty-Personal Care",
    "Watches",
    "Furniture",
    "Sports and Entertainment",
  "Hair extensions-Wigs", 
    "Health-Wellness",
  ];
  
