export const universities = [
  "Strathmore University",
  "Riara University",
  "University of Nairobi",
  "Kenyatta University",
  "Multimedia University of Kenya",
  "Dedan Kimathi University of Technology",
  "Cooperative University of Kenya",
  "Jomo Kenyatta University of Agriculture and Technology",
  "Mount Kenya University",
  "Meru University of Science and Technology",
  "Technical University of Kenya",
  "Africa Nazarene University",
  "United States International University",
  "Catholic University of Eastern Africa",
  "Daystar University",
  "KCA University",
  "Aga Khan University",
  "Technical University of Mombasa",
  "Mount Kenya University",
  "Pan Africa Christian University",
  "Scott Christian University",

  "Egerton University",
  "Moi University",
  "Maseno University",

  "Kisii University",
  "Karatina University",
  "Murang'a University of Technology",
  "University of Eldoret",
  "University of Kabianga",
  "Chuka University",
  "Laikipia University",
  "South Eastern Kenya University",

  "Kirinyaga University",
  "Kibabii University",
  "Rongo University",
  "Maasai Mara University",
  "Kisii University",
  "Karatina University",
];
